apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kzdv-dev
  namespace: dev
spec:
  secretName: kzdv-dev-tls
  issuerRef:
    name: letsencrypt-zdv
    kind: ClusterIssuer
  dnsNames:
  - kzdv.dev
  - '*.kzdv.dev'
